### ISSUE TITLE
Chapter 3: LSD example

### ISSUE THREAD

**Issue by aderzelle** [chrisvoncsefalvay/learn-julia-the-hard-way#48]
Hello,

The LSD example doesn't seem "to work" for me.

```julia
      type LSD
       pounds::Int
       shillings::Int
       pence::Int
       function LSD(l,s,d)
       if l < 0 || s < 0 || d < 0
       error("No negative")
       end
       if d > 12 || s > 20
       error("Too many pence or shillings")
       end
       new(l,s,d)
       end
       end
```

I get

```julia
tomato = LSD(0, 50, 50)
LSD(0,50,50)
```
julia doesn't complain that s and d are over 20 and 12. 
Has the syntax changed after the tutorial publication? 
Thanks a lot.

**Comment by chrisvoncsefalvay** [comment]
In all likelihood it has! Or it's tripping on the LSD. No pun intended ;))) 

I'll take a detailed look at this once I am at a proper computer. Thanks for reading, and for spotting this!

**Comment by KlausC** [comment]
In v0.6 that works as expected. The keyword `type` should be replaced by `struct`.
